## 24ADI204 DATA SCIENCE AND VISULIZATION


### PROBLEM STATEMENT :
#### Smart Farming Analytics: Crop Recommendation and Agricultural Condition Analysis

### Domain:
#### Agriculture & Smart Farming



### Dataset Source:
**Dataset Name:** Smart Farming Recommendation Dataset

**Source:** User-provided CSV dataset

**Dataset link:** https://www.kaggle.com/datasets/hariharank2205/smart-agriculture


**Dataset file:** 'C:\Users\ELCOT\Documents\SmartFarming_recommendation.csv'

### SDG Aligned
**SDG 2 – Zero Hunger**

This project is aligned with Sustainable Development Goal 2 by using data-driven analysis to support crop recommendation, efficient resource use, and improved agricultural decision-making.

### Team Number: 13

### Team Members:
Hadhish R

Hariharan K

Prasanna M

Siva Deepan A

### Objective of Week 2
The objective of this week's work is to understand the raw dataset before performing data cleaning and Exploratory Data Analysis (EDA). The dataset will be inspected to understand its size, structure, features, data types, missing values, duplicate records, and overall data quality.

# 1. Import Required Libraries and Load the Dataset

**Purpose:** Import the libraries required for data analysis and visualization and Load the raw dataset into a Pandas DataFrame for analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\ELCOT\Documents\SmartFarming_recommendation.csv")

# 2. View Sample Records

**Purpose:** Get an initial view of the dataset and its values and also the final view

In [2]:
df.head()

,N,P,K,temperature,humidity,ph,rainfall,label,soil_moisture,soil_type,...,organic_matter,irrigation_frequency,crop_density,pest_pressure,fertilizer_usage,growth_stage,urban_area_proximity,water_source_type,frost_risk,water_usage_efficiency
0,90.0,42.0,43.0,20.879744,82.002744,6.502985,202.935536,rice,29.446064,2.0,...,3.121395,4.0,NaN,57.607308,188.194958,1.0,2.719614,3.0,95.649985,1.193293
1,85.0,58.0,41.0,21.770462,80.319644,7.038096,226.655537,rice,12.851183,3.0,...,2.142021,4.0,NaN,NaN,70.963629,1.0,4.714427,2.0,77.265694,1.752672
2,60.0,55.0,44.0,NaN,82.320763,7.840207,263.964248,rice,29.363913,2.0,...,1.474974,1.0,12.654395,1.034478,191.976077,1.0,30.431736,2.0,18.192168,3.035541
3,74.0,35.0,40.0,26.491096,80.158363,6.980401,242.864034,rice,26.207732,3.0,...,8.393907,1.0,10.864360,24.091888,55.761388,3.0,10.861071,3.0,82.818720,1.273341
4,78.0,42.0,42.0,20.130175,81.604873,7.628473,262.717340,rice,28.236236,2.0,...,NaN,3.0,13.852910,38.811481,185.259702,2.0,47.190777,3.0,25.466499,2.578671

In [3]:
df.tail()

,N,P,K,temperature,humidity,ph,rainfall,label,soil_moisture,soil_type,...,organic_matter,irrigation_frequency,crop_density,pest_pressure,fertilizer_usage,growth_stage,urban_area_proximity,water_source_type,frost_risk,water_usage_efficiency
2305,NaN,64.0,16.0,16.433403,NaN,5.926677,140.371781,kidneybeans,25.651886,2.0,...,9.521419,1.0,8.559229,12.564164,148.332914,2.0,9.757609,1.0,93.896347,4.324427
2306,NaN,NaN,53.0,NaN,84.608083,6.211749,42.006603,watermelon,17.992056,1.0,...,9.853923,2.0,18.613574,90.999114,185.338434,3.0,0.900658,2.0,76.141116,3.514959
2307,NaN,82.0,45.0,25.293915,79.291222,5.614471,105.422025,banana,15.584397,2.0,...,8.628985,1.0,18.495212,32.374102,64.545467,2.0,36.529246,3.0,92.074148,3.046822
2308,NaN,63.0,19.0,19.347944,55.968055,4.681576,194.592115,pigeonpeas,28.003393,2.0,...,4.360637,6.0,5.815317,8.527237,109.748746,2.0,38.501070,1.0,39.352987,3.395942
2309,NaN,NaN,21.0,31.019636,49.976752,3.532009,32.812965,mothbeans,16.289118,2.0,...,9.792096,6.0,8.752278,24.328156,178.829449,3.0,6.238500,NaN,23.543122,3.421367

# 3. Check Dataset Shape and Check Column Names

**Purpose:** Identify the number of rows and columns in the dataset and Identify all available features in the dataset.

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

Rows: 2310
Columns: 23

Column Names:
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label', 'soil_moisture', 'soil_type', 'sunlight_exposure', 'wind_speed', 'co2_concentration', 'organic_matter', 'irrigation_frequency', 'crop_density', 'pest_pressure', 'fertilizer_usage', 'growth_stage', 'urban_area_proximity', 'water_source_type', 'frost_risk', 'water_usage_efficiency']

# 4. Check Dataset Information

**Purpose:** Understand the dataset structure, data types, and non-null values.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2310 entries, 0 to 2309
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   N                       2090 non-null   float64
 1   P                       2194 non-null   float64
 2   K                       2194 non-null   float64
 3   temperature             2196 non-null   float64
 4   humidity                2196 non-null   float64
 5   ph                      2196 non-null   float64
 6   rainfall                2196 non-null   float64
 7   label                   2310 non-null   object
 8   soil_moisture           2193 non-null   float64
 9   soil_type               2193 non-null   float64
 10  sunlight_exposure       2196 non-null   float64
 11  wind_speed              2194 non-null   float64
 12  co2_concentration       2196 non-null   float64
 13  organic_matter          2191 non-null   float64
 14  irrigation_frequency    2192 non-null   float64
 15  crop_density            2193 non-null   float64
 16  pest_pressure           2195 non-null   float64
 17  fertilizer_usage        2197 non-null   float64
 18  growth_stage            2193 non-null   float64
 19  urban_area_proximity    2191 non-null   float64
 20  water_source_type       2196 non-null   float64
 21  frost_risk              2198 non-null   float64
 22  water_usage_efficiency  2194 non-null   float64
dtypes: float64(22), object(1)
memory usage: 415.2+ KB

# 5. Identify Feature Types

**Purpose:** Separate numerical and categorical features for further analysis.

In [6]:
numerical_cols = df.select_dtypes(
    include=np.number
).columns.tolist()

categorical_cols = df.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

print("Numerical Features:")
print(numerical_cols)

print("\nCategorical Features:")
print(categorical_cols)

Numerical Features:
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'soil_moisture', 'soil_type', 'sunlight_exposure', 'wind_speed', 'co2_concentration', 'organic_matter', 'irrigation_frequency', 'crop_density', 'pest_pressure', 'fertilizer_usage', 'growth_stage', 'urban_area_proximity', 'water_source_type', 'frost_risk', 'water_usage_efficiency']

Categorical Features:
['label']

# 6. Check Missing Values

**Purpose:** Identify missing values and assess data completeness.

In [7]:
df.isnull().sum()

N                         220
P                         116
K                         116
temperature               114
humidity                  114
ph                        114
rainfall                  114
label                       0
soil_moisture             117
soil_type                 117
sunlight_exposure         114
wind_speed                116
co2_concentration         114
organic_matter            119
irrigation_frequency      118
crop_density              117
pest_pressure             115
fertilizer_usage          113
growth_stage              117
urban_area_proximity      119
water_source_type         114
frost_risk                112
water_usage_efficiency    116
dtype: int64

# 7. Check Duplicate Records

**Purpose:** Identify duplicate observations in the dataset.

In [8]:
df.duplicated().sum()

np.int64(110)

# 8. Check Unique Values

**Purpose:** Identify the number of unique values in each feature.

In [9]:
df.nunique()

N                          137
P                          117
K                           73
temperature               2090
humidity                  2090
ph                        2090
rainfall                  2090
label                       22
soil_moisture             2090
soil_type                    3
sunlight_exposure         2090
wind_speed                2090
co2_concentration         2090
organic_matter            2090
irrigation_frequency         6
crop_density              2090
pest_pressure             2090
fertilizer_usage          2090
growth_stage                 3
urban_area_proximity      2090
water_source_type            3
frost_risk                2090
water_usage_efficiency    2090
dtype: int64

# 9. Statistical Summary

**Purpose:** Understand the basic statistical characteristics of numerical features.

In [10]:
df.describe(include="all")

,N,P,K,temperature,humidity,ph,rainfall,label,soil_moisture,soil_type,...,organic_matter,irrigation_frequency,crop_density,pest_pressure,fertilizer_usage,growth_stage,urban_area_proximity,water_source_type,frost_risk,water_usage_efficiency
count,2090.000000,2194.000000,2194.000000,2196.000000,2196.000000,2196.000000,2196.000000,2310,2193.000000,2193.000000,...,2191.000000,2192.000000,2193.000000,2195.000000,2197.000000,2193.000000,2191.000000,2196.000000,2198.000000,2194.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,papaya,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,50.548325,53.066089,47.326345,25.671178,71.518719,6.474704,103.472411,NaN,20.165078,1.988144,...,5.462752,3.515967,12.355451,49.706340,125.956204,2.006840,24.539122,1.996357,50.077145,3.000466
std,37.027836,32.736783,49.735967,5.009890,22.235590,0.775918,55.196194,NaN,5.796658,0.809301,...,2.616503,1.699926,4.315593,28.882339,43.531360,0.818607,14.488093,0.814440,28.439171,1.137709
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267,NaN,10.024260,1.000000,...,1.003338,1.000000,5.006916,0.038103,50.209990,1.000000,0.017756,1.000000,0.054911,1.004173
25%,21.000000,28.000000,20.000000,22.851637,60.261953,5.980442,64.236408,NaN,15.201741,1.000000,...,3.164297,2.000000,8.572043,24.238190,88.368873,1.000000,12.066608,1.000000,25.937471,2.062994
50%,37.000000,51.000000,31.000000,25.656980,80.454888,6.429964,94.695862,NaN,20.162879,2.000000,...,5.406924,4.000000,12.306141,49.440328,126.163510,2.000000,24.448096,2.000000,49.729476,2.975677
75%,85.000000,68.000000,48.000000,28.572096,90.026054,6.927832,124.267508,NaN,25.314461,3.000000,...,7.694495,5.000000,16.001342,74.407407,163.916230,3.000000,36.855375,3.000000,75.034170,3.981608
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117,NaN,29.997860,3.000000,...,9.999990,6.000000,19.988474,99.983849,199.982166,3.000000,49.992046,3.000000,99.957274,4.997130

# 10. Check Constant Columns

**Purpose:** Identify columns with only one unique value.

In [11]:
constant_columns = [
    col for col in df.columns
    if df[col].nunique() == 1
]

print(constant_columns)

[]

# 11. Data Quality Summary

**Purpose:** Summarize the quality and characteristics of each feature.

In [12]:
data_quality_report = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Missing %": ((df.isnull().sum() / len(df)) * 100).round(2),
    "Unique Values": df.nunique()
})

data_quality_report

                       Data Type  Missing Values  Missing %  Unique Values
N                        float64             220       9.52            137
P                        float64             116       5.02            117
K                        float64             116       5.02             73
temperature              float64             114       4.94           2090
humidity                 float64             114       4.94           2090
ph                       float64             114       4.94           2090
rainfall                 float64             114       4.94           2090
label                     object               0       0.00             22
soil_moisture            float64             117       5.06           2090
soil_type                float64             117       5.06              3
sunlight_exposure        float64             114       4.94           2090
wind_speed               float64             116       5.02           2090
co2_concentration        float64             114       4.94           2090
organic_matter           float64             119       5.15           2090
irrigation_frequency     float64             118       5.11              6
crop_density             float64             117       5.06           2090
pest_pressure            float64             115       4.98           2090
fertilizer_usage         float64             113       4.89           2090
growth_stage             float64             117       5.06              3
urban_area_proximity     float64             119       5.15           2090
water_source_type        float64             114       4.94              3
frost_risk               float64             112       4.85           2090
water_usage_efficiency   float64             116       5.02           2090

### Week 2 Conclusion

The raw dataset was successfully inspected to understand its structure, features, data types, missing values, duplicates, and overall data quality.

The next stage will focus on data cleaning and preparation.